import type { ReactNode } from 'react';
import type { Signal } from '../../../shared/stats';
import type { AiResult, Kid, QuestCategory } from '../../../shared/types';
import { Icon } from './Icon';
import type { IconName } from './Icon';

export function Card({
  title,
  subtitle,
  icon,
  actions,
  children,
  className = '',
}: {
  title?: ReactNode;
  subtitle?: ReactNode;
  icon?: IconName;
  actions?: ReactNode;
  children: ReactNode;
  className?: string;
}) {
  return (
    <section className={`card ${className}`}>
      {(title || actions) && (
        <header className="card-head">
          <div>
            {title && (
              <h2 className="card-title">
                {icon && <Icon name={icon} size={18} />}
                {title}
              </h2>
            )}
            {subtitle && <p className="card-sub">{subtitle}</p>}
          </div>
          {actions && <div className="card-actions">{actions}</div>}
        </header>
      )}
      {children}
    </section>
  );
}

export type DeltaTone = 'good' | 'bad' | 'flat';

export function StatTile({
  label,
  value,
  unit,
  delta,
  hint,
}: {
  label: string;
  value: ReactNode;
  unit?: string;
  delta?: { text: string; tone: DeltaTone; direction?: 'up' | 'down' };
  hint?: string;
}) {
  return (
    <div className="tile">
      <div className="tile-label">{label}</div>
      <div className="tile-value">
        {value}
        {unit && <small>{unit}</small>}
      </div>
      {delta && (
        <div className={`tile-delta delta-${delta.tone}`}>
          {delta.direction && <Icon name={delta.direction} size={14} />}
          {delta.text}
        </div>
      )}
      {hint && <div className="tile-hint">{hint}</div>}
    </div>
  );
}

export function modelLabel(model?: string): string {
  if (!model) return 'Claude';
  const parts = model.replace(/^anthropic\./, '').split('-');
  const words = parts.filter((p) => Number.isNaN(Number(p))).map((p) => p.charAt(0).toUpperCase() + p.slice(1));
  const version = parts.filter((p) => !Number.isNaN(Number(p))).join('.');
  return `${words.join(' ')} ${version}`.trim();
}

export function SourceTag({ result }: { result: AiResult<unknown> }) {
  if (result.source === 'claude') {
    return (
      <span className="pill pill-ai" title={`Generated by ${result.model} on Amazon Bedrock`}>
        <Icon name="sparkle" size={12} />
        {modelLabel(result.model)} · Amazon Bedrock
      </span>
    );
  }
  return (
    <span className="pill pill-rules" title={result.note ?? 'Generated by Anchor’s rules engine'}>
      <Icon name="chart" size={12} />
      Rules engine
    </span>
  );
}

export function FallbackNote({ result }: { result: AiResult<unknown> }) {
  if (result.source === 'claude') return null;
  return (
    <p className="fallback-note">
      <Icon name="info" size={14} />
      <span>
        Claude wasn’t available for this one, so Anchor’s rules engine wrote it from the same signals.
        {result.note && <span className="fallback-reason"> ({result.note})</span>}
      </span>
    </p>
  );
}

export const CATEGORY_LABELS: Record<QuestCategory, string> = {
  learning: 'Learning',
  life: 'Life skills',
  wellbeing: 'Wellbeing',
  school: 'School',
};

export function CategoryPill({ category }: { category: QuestCategory }) {
  return <span className={`pill pill-cat pill-${category}`}>{CATEGORY_LABELS[category]}</span>;
}

export function SignalIcon({ tone }: { tone: Signal['tone'] }) {
  if (tone === 'positive') return <Icon name="check" size={16} className="signal-icon signal-positive" />;
  if (tone === 'watch') return <Icon name="alert" size={16} className="signal-icon signal-watch" />;
  return <Icon name="info" size={16} className="signal-icon signal-neutral" />;
}

export function KidTabs({ kids, value, onChange, label }: { kids: Kid[]; value: string; onChange: (id: string) => void; label: string }) {
  return (
    <div className="kid-tabs" role="tablist" aria-label={label}>
      {kids.map((kid) => (
        <button
          key={kid.id}
          type="button"
          role="tab"
          aria-selected={kid.id === value}
          className="kid-tab"
          onClick={() => onChange(kid.id)}
        >
          <span className="kid-tab-avatar" aria-hidden="true">
            {kid.avatar}
          </span>
          <span>
            <strong>{kid.name}</strong>
            <small>
              {kid.age} · {kid.grade}
            </small>
          </span>
        </button>
      ))}
    </div>
  );
}

export function Loading({ label }: { label: string }) {
  return (
    <div className="loading" role="status">
      <span className="loading-dot" aria-hidden="true" />
      {label}
    </div>
  );
}
